[package]
name = "spokes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shortcodes"
path = "src/shortcodes.rs"

[dependencies]
bnacore = { path = "../bnacore" }
clap = { version = "4.0.8", features = ["cargo", "derive"] }
color-eyre = "0.6.2"
